Hannah/table controls
ccmbioinfo/osmp pull request #19
Opened 2021-08-03 14:26 UTC by hannahle

- Added table sorting, pagination, general and advanced filters
- Replace logos from Material UI with react-icons

2021-08-03 14:47 UTC, hannahle commented on react/src/react-table-config.d.ts
> + * This config file is required for hooks to work in Table.tsx.
I wasn't able to use some built-in hooks in react-table and followed the steps here: https://github.com/tannerlinsley/react-table/blob/master/TYPESCRIPT.md to fix it

2021-08-03 15:50 UTC, cklamann requested changes
Looks really good! I made a couple of comments about the inputs -- I'm not sure if it's straightforward to remove local state, but could you please take a look and see if it's possible?

2021-08-03 15:50 UTC, cklamann commented on react/src/components/Input.tsx
> +    value: any;
I think this can be number or string. We might just default to string and let handler functions take care of conversions if necessary.

2021-08-03 15:50 UTC, cklamann commented on react/src/components/Table/ColumnFilter.tsx
> +    const [value, setValue] = useState('');
Can you make this component controlled so that it takes `state.filters` as a prop rather than storing the filter value in local state?

2021-08-03 15:50 UTC, cklamann commented on react/src/components/Table/GlobalFilters.tsx
> +export const GlobalFilter: React.FC<GlobalFilterProps> = ({ filter, setFilter }) => {
Can this also be controlled, with local state removed?

2021-08-04 12:55 UTC, cklamann approved these changes

2021-08-04 13:59 UTC, merged