Draft: DevOps: Deploy to production
ccmbioinfo/osmp pull request #294
Opened 2022-07-25 13:00 UTC by jennyziyi-xu

- Github workflow files are created for deploying React, `server` and `keycloak` containers in production. 
- `docker-compose.prod.yaml` is created for deploying `server` and `keycloak` containers. 

- [ ] @frewmack The "keycloak" sections are identical to those in the files for the staging instance. Please feel free to modify if necessary. 
- [ ] This PR is pending on domain DNS registration, MongoDB database and integration with Phenotips staging or production. 

Here is a list of secrets, feel free to add secrets to the environment `OSMP_PROD` when they are obtained. 

React:

- [ ]  REACT_APP_GRAPHQL_URL (pending on domain name)
- [ ]  REACT_APP_KEYCLOAK_AUTH_URL
- [ ]  REACT_APP_KEYCLOAK_REALM
- [ ]  REACT_APP_KEYCLOAK_CLIENT_ID
- [ ] REACT_SOURCE_LIST
- [ ] MC_HOST
- [ ] MINIO_BUCKET

Server and Mongo:

- [ ] G4RD_AUTH_METHOD
- [ ]  G4RD_PASSWORD
- [ ]  G4RD_URL
- [ ]  G4RD_USERNAME
- [ ]  G4RD_REALM
- [ ]  G4RD_GRANT_TYPE
- [ ]  G4RD_TOKEN_URL
- [ ]  G4RD_CLIENT_ID
- [ ]  G4RD_AUTH0_BASE_URL
- [ ]  MONGO_CONNECTION_STRING (pending on account creation)

Keycloak

- [ ]  KEYCLOAK_DB_ADDR
- [ ]  KEYCLOAK_DB
- [ ]  KEYCLOAK_DB_USER
- [ ]  KEYCLOAK_DB_PASSWORD
- [ ]  KEYCLOAK_REALM
- [ ]  KEYCLOAK_AUTH_URL
- [ ]  KEYCLOAK_CLIENT_ID

SSH Config

- [ ]  DEPLOY_PRIVATE_KEY
- [ ]  DEPLOY_HOST_KEY
- [ ]  DEPLOY_SSH_HOST

2022-07-26 20:19 UTC, frewmack requested changes

2022-07-26 20:19 UTC, frewmack commented on docker-compose.prod.yaml
> +      KEYCLOAK_FRONTEND_URL: "https://keycloak.ccmdev.ca/auth"
```suggestion
      KEYCLOAK_FRONTEND_URL: "https://keycloak.osmp.genomics4rd.ca/auth"
```

2022-07-27 13:11 UTC, frewmack commented
Added Keycloak secrets. Credentials for linking Keycloak to G4RD's Auth0 instance will have to be put in place after production goes up.

2022-07-27 15:04 UTC, themisteryang commented
Added the `MONGO_CONNECTION_STRING` secret to the `OSMP_PROD` environment!

2022-07-28 15:49 UTC, themisteryang approved these changes
LGTM! 🚀

2022-07-28 15:50 UTC, frewmack approved these changes
Changes look good! I think we can merge this to develop, and then merge our first release from develop onto production once the proxy changes are pushed on the CHEO RI infrastructure repo.

2022-07-28 16:05 UTC, jennyziyi-xu commented
Sounds good to me!

2022-07-28 16:44 UTC, merged