React: Edit About page
ccmbioinfo/osmp pull request #296
Opened 2022-07-27 17:42 UTC by jennyziyi-xu

2022-08-03 15:31 UTC, frewmack requested changes

2022-08-03 15:31 UTC, frewmack commented on react/src/pages/About.tsx
> +                        allows the queriors to filter and sort variant/participant information to
```suggestion
                        allows you to filter and sort variant/participant information to
```

2022-08-03 15:31 UTC, frewmack commented on react/src/pages/About.tsx
> +                                OSMP "liftOver" these variants from their original genome assembly
```suggestion
                                OSMP "lifts over" these variants from their original genome assembly
```

2022-08-03 15:46 UTC, themisteryang commented on react/src/pages/About.tsx
> +                                assembly in the variant store. The column "Current Assembly"
```suggestion
                                . The "Original Assembly" column displays the variant's genome
                                assembly in the variant store. The "Current Assembly" column
```

2022-08-03 16:17 UTC, themisteryang requested changes

2022-08-03 16:17 UTC, themisteryang commented on react/src/pages/About.tsx
> +                                stores from one or multiple contributors. The result table will
```suggestion
                                stores from one or more contributors. The result table will
```

2022-08-03 16:17 UTC, themisteryang commented on react/src/pages/About.tsx
> +                                assembly in the variant store. The column "Current Assembly"
```suggestion
                                . The "Original Assembly" column displays the variant's genome
                                assembly in the variant store. The "Current Assembly" column
```

2022-08-05 18:51 UTC, frewmack approved these changes
LGTM!

2022-08-05 21:09 UTC, themisteryang approved these changes
LGTM! 🚀

2022-08-08 13:35 UTC, merged